type PointSlug = `${number},${number}`;
type Entity = {
    x: number;
    y: number;
    hp: number;
    sprite: number;
};
declare const SPRITES: readonly [readonly [60, 64, 84, 64, 60, 126, 36], readonly [0, 56, 124, 84, 124, 84, 0], readonly [60, 24, 24, 36, 66, 126, 60], readonly [126, 120, 100, 20, 84, 84, 126], readonly [16, 16, 16, 16, 56, 16, 0], readonly [0, 126, 92, 106, 118, 106, 92], readonly [0, 36, 60, 40, 60, 126, 36]];
declare const VIEWSIZE = 9;
declare const TILESIZE = 7;
declare const TILE_FLOOR = 3;
declare const TILE_POTION = 5;
declare const TILE_STAIRS = 6;
declare const TILE_SWORD = 7;
declare const SPRITE_PLAYER = 0;
declare const SPRITE_MONSTER = 1;
declare const SPRITE_POTION = 2;
declare const SPRITE_STAIRS = 3;
declare const SPRITE_SWORD = 4;
declare const SPRITE_EXIT = 5;
declare const SPRITE_MONSTER2 = 6;
declare const PALETTE = "fd9640";
declare const KEY_LEFT = 37;
declare const KEY_UP = 38;
declare const KEY_RIGHT = 39;
declare const KEY_DOWN = 40;
declare const canvas: HTMLCanvasElement;
declare const ctx: CanvasRenderingContext2D;
declare let level: number;
declare let swordAmount: number;
declare let mapData: Record<PointSlug, number>;
declare let mobs: Entity[];
declare let mobIndex: Record<PointSlug, number>;
declare const pointSlug: (x: number, y: number) => PointSlug;
declare const getMobIndexAt: (x: number, y: number) => number;
declare const indexMob: (idx: number) => void;
declare const removeMobIndex: (x: number, y: number) => void;
declare const moveMob: (idx: number, nx: number, ny: number) => void;
declare const deltaFromKey: (code: number) => {
    dx: number;
    dy: number;
};
declare const randInt: (exclMax: number) => number;
declare const draw: () => void;
declare const createMap: (playerHealth: number) => void;
declare const processTurn: (keyCode: number) => void;
